#!/bin/bash

# change the path to were this script is stored
cd "$( dirname "${BASH_SOURCE[0]}" )"

# delete the old SpinningTop.app
rm -r SpinningTop.app

g++ src/*.cpp -I /usr/local/include -I include -L /usr/local/lib -lglfw3 -lGLEW -lSOIL -lassimp -framework OpenGL -std=c++11 -o SpinningTops -headerpad_max_install_names

mkdir SpinningTop.app
mkdir SpinningTop.app/Contents
mkdir SpinningTop.app/Contents/MacOS
mkdir SpinningTop.app/Contents/Resources

echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">
<plist version=\"1.0\">
<dict>
<key>CFBundleGetInfoString</key>
<string>SpinningTop</string>
<key>CFBundleExecutable</key>
<string>launchScript</string>
<key>CFBundleIdentifier</key>
<string>ch.tzmb.SpinningTop</string>
<key>CFBundleName</key>
<string>SpinningTop</string>
<key>CFBundleIconFile</key>
<string>iconfile</string>
<key>CFBundleShortVersionString</key>
<string>1.0</string>
<key>CFBundleInfoDictionaryVersion</key>
<string>6.0</string>
<key>CFBundlePackageType</key>
<string>APPL</string>
</dict>
</plist>" > SpinningTop.app/Contents/Info.plist

mv SpinningTops SpinningTop.app/Contents/MacOS/
cp -r models SpinningTop.app/Contents/Resources/
cp -r shaders SpinningTop.app/Contents/Resources/
cp -r textures SpinningTop.app/Contents/Resources/
cp iconfile.icns SpinningTop.app/Contents/Resources/

echo "#!/bin/bash
cd \"\${0%/*}\"
./SpinningTops" > SpinningTop.app/Contents/MacOS/launchScript
chmod +x SpinningTop.app/Contents/MacOS/launchScript

otool -L SpinningTop.app/Contents/MacOS/SpinningTops | grep -o "/.*dylib" | grep -v "/System/Library/" | grep -v "/usr/lib/" | grep -v "libSOIL" | xargs -I {} cp {} SpinningTop.app/Contents/MacOS/ 
# otool listet libSOIL falsch auf. Muss deshalb extra behandelt werden
cp /usr/local/lib/libSOIL.dylib SpinningTop.app/Contents/MacOS/

ls SpinningTop.app/Contents/MacOS/ | grep "dylib" | xargs -I {} chmod 755 SpinningTop.app/Contents/MacOS/{} 

libPaths=$(otool -L SpinningTop.app/Contents/MacOS/SpinningTops | grep -o "/.*dylib" | grep -v "/System/Library/" | grep -v "/usr/lib/") 
for i in $libPaths 
do 
    install_name_tool -change $i @executable_path/$(echo $i | grep -o "lib\(\w*\.\)*dylib" | xargs echo) SpinningTop.app/Contents/MacOS/SpinningTops 
done

